import React, { useContext, useState } from 'react'
import { useParams } from 'react-router-dom'
import { AuthContext } from '../../context/AuthContext'
import { useHttp } from '../../hooks/http.hook'
import { Loader } from '../../components/loader/Loader'
import { useNavigate } from 'react-router-dom'

export const UpdateWeekPage = ({weeks}) => {
    const { request, loading } = useHttp()
    const navigate = useNavigate()
    const auth = useContext(AuthContext)
    const groopLogin = useParams().login
    const [week, setWeek] = useState({});
    const changeHandler = event => {
        setWeek({ ...week, [event.target.name]: event.target.value })
    }

    const weeks1=weeks

    const addHandler = async () => {

        try {
            console.log('Data', week)
            console.log(groopLogin)
            const data = await request(`/api/user/${groopLogin}/update`, 'POST', { ...week }, {    
                Authorization: `Bearer ${auth.token}`
            })

            
            navigate(`/groop/${groopLogin}`)
        } catch (e) { }

    }
    const falseHandler = async () => {

        try {
            navigate(`/groop/${groopLogin}`)
        } catch (e) { }

    }

    if (loading) {
        return <Loader />
    }

    return (

        <>

            <div>
                <table>
                    <thead>
                        <tr>
                            <th >№</th>
                            <th>Понедельник</th>
                            <th>Вторник</th>
                            <th>Среда</th>
                            <th>Четверг</th>
                            <th>Пятница</th>
                            <th>Суббота</th>
                            <th>Воскресение</th>
                        </tr>
                    </thead>
                    <tbody>

                        <tr>
                            <td>1</td>
                            <td>
                                <input  
                                    name='mondayfirstLesson'
                                    type="text"
                                    value={week.mondayfirstLesson}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='tuesdayfirstLesson'
                                    type="text"
                                    value={week.firtsles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='wednesdayfirstLesson'
                                    type="text"
                                    value={week.firtsles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='thirthdayfirstLesson'
                                    type="text"
                                    value={week.firtsles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='fridayfirstLesson'
                                    type="text"
                                    value={week.firtsles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='saturdayfirstLesson'
                                    type="text"
                                    value={week.firtsles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='sundayfirstLesson'
                                    type="text"
                                    value={week.firtsles}
                                    onChange={changeHandler}
                                />
                            </td>
                        </tr>
                        {/* <tr>
                            <td>2</td>
                            <td>
                                <input
                                    name='mondaysecondLesson'
                                    type="text"
                                    value={week.secondles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='tues2'
                                    type="text"
                                    value={week.secondles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='wed2'
                                    type="text"
                                    value={week.secondles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='thir2'
                                    type="text"
                                    value={week.secondles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='fri2'
                                    type="text"
                                    value={week.secondles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='sat2'
                                    type="text"
                                    value={week.secondles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='sun2'
                                    type="text"
                                    value={week.secondles}
                                    onChange={changeHandler}
                                />
                            </td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>
                                <input
                                    name='mondaythirdLesson'
                                    type="text"
                                    value={week.thirdles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='tues3'
                                    type="text"
                                    value={week.thirdles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='wed3'
                                    type="text"
                                    value={week.thirdles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='thir3'
                                    type="text"
                                    value={week.thirdles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='fri3'
                                    type="text"
                                    value={week.thirdles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='sat3'
                                    type="text"
                                    value={week.thirdles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='sun3'
                                    type="text"
                                    value={week.thirdles}
                                    onChange={changeHandler}
                                />
                            </td>
                        </tr>
                        <tr>
                            <td>4</td>
                            <td>
                                <input
                                    name='mondayfourthLesson'
                                    type="text"
                                    value={week.fourles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='tues4'
                                    type="text"
                                    value={week.fourles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='wed4'
                                    type="text"
                                    value={week.fourles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='thir4'
                                    type="text"
                                    value={week.fourles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='fri4'
                                    type="text"
                                    value={week.ffourles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='sat4'
                                    type="text"
                                    value={week.fourles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='sun4'
                                    type="text"
                                    value={week.fourles}
                                    onChange={changeHandler}
                                />
                            </td>
                        </tr>
                        <tr>
                            <td>5</td>
                            <td>
                                <input
                                    name='mon5'
                                    type="text"
                                    value={week.fifthles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='tues5'
                                    type="text"
                                    value={week.fifthles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='wed5'
                                    type="text"
                                    value={week.fifthles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='thir5'
                                    type="text"
                                    value={week.fifthles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='fri5'
                                    type="text"
                                    value={week.fifthles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='sat5'
                                    type="text"
                                    value={week.fifthles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='sun5'
                                    type="text"
                                    value={week.fifthles}
                                    onChange={changeHandler}
                                />
                            </td>
                        </tr>
                        <tr>
                            <td>6</td>
                            <td>
                                <input
                                    name='mon6'
                                    type="text"
                                    value={week.sixthles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='tues6'
                                    type="text"
                                    value={week.sixthles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='wed6'
                                    type="text"
                                    value={week.sixthles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='thir6'
                                    type="text"
                                    value={week.sixthles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='fri6'
                                    type="text"
                                    value={week.sixthles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='sat6'
                                    type="text"
                                    value={week.sixthles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='sun6'
                                    type="text"
                                    value={week.sixthles}
                                    onChange={changeHandler}
                                />
                            </td>
                        </tr>
                        <tr>
                            <td>7</td>
                            <td>
                                <input
                                    name='mon7'
                                    type="text"
                                    value={week.sevenhles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='tues7'
                                    type="text"
                                    value={week.sevenles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='wed7'
                                    type="text"
                                    value={week.sevenles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='thir7'
                                    type="text"
                                    value={week.sevenles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='fri7'
                                    type="text"
                                    value={week.sevenles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='sat7'
                                    type="text"
                                    value={week.sevenles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='sun7'
                                    type="text"
                                    value={week.sevenles}
                                    onChange={changeHandler}
                                />
                            </td>
                        </tr>
                        <tr>
                            <td>8</td>
                            <td>
                                <input
                                    name='mon8'
                                    type="text"
                                    value={week.eithles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='tues8'
                                    type="text"
                                    value={week.eithles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='wed8'
                                    type="text"
                                    value={week.eithles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='thir8'
                                    type="text"
                                    value={week.eithles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='fri8'
                                    type="text"
                                    value={week.eithles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='sat8'
                                    type="text"
                                    value={week.eithles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='sun8'
                                    type="text"
                                    value={week.eithles}
                                    onChange={changeHandler}
                                />
                            </td>
                        </tr>
                        <tr>
                            <td>9</td>
                            <td>
                                <input
                                    name='mon9'
                                    type="text"
                                    value={week.nineles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='tues9'
                                    type="text"
                                    value={week.nineles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='wed9'
                                    type="text"
                                    value={week.nineles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='thir9'
                                    type="text"
                                    value={week.nineles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='fri9'
                                    type="text"
                                    value={week.nineles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='sat9'
                                    type="text"
                                    value={week.nineles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='sun9'
                                    type="text"
                                    value={week.nineles}
                                    onChange={changeHandler}
                                />
                            </td>
                        </tr>
                        <tr>
                            <td>10</td>
                            <td>
                                <input
                                    name='mon10'
                                    type="text"
                                    value={week.tenles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='tues10'
                                    type="text"
                                    value={week.tenles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='wed10'
                                    type="text"
                                    value={week.tenles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='thir10'
                                    type="text"
                                    value={week.tenles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='fri10'
                                    type="text"
                                    value={week.tenles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='sat10'
                                    type="text"
                                    value={week.tenles}
                                    onChange={changeHandler}
                                />
                            </td>
                            <td>
                                <input
                                    name='sun10'
                                    type="text"
                                    value={week.tenles}
                                    onChange={changeHandler}
                                />
                            </td>
                        </tr> */}
                    </tbody>
                </table>
            </div>

            <button className="btn " onClick={falseHandler}>Отмена</button>
            <button className="btn " onClick={addHandler}>Сохранить расписание</button>

        </>

    )

}